# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7210f30b10ff2a76f4db2f984ba0705608776dc9240cdf442eef8b38e0ae8f864344dcdf670073e4acdd7030ba6e0a0bdf2d6c9e05a74f9827e069318774754

test:
  secret_key_base: ae715e2141a0d0fc3ae7299fadbe2cb6764fb54c74099faa3b0922754590d9827a968ae55ae2c1d21b80d07ec7f351655333378486567e3d4e4e589ba8a27958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
